name: Dart Release

on:
  push:
    branches:
      - main
      - next

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: dart-lang/setup-dart@v1

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish on pub.dev
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.PUBLISH_CREDENTIALS }}
